config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/auth/github', :as => 'auth_github'

  get '/auth/github/callback' => 'sessions#create'

  delete 'logout' => 'sessions#destroy', :as => 'logout'

  get '/organizations' => 'organizations#index', :as => 'organizations'

  get '/organizations/:organization' => 'organizations#show', :as => 'organization', :constraints  => { :organization => /[-0-z\._]+/ }

  get '/organizations/:organization/repos/:repo' => 'repos#show', :as => 'repo', :constraints  => { :repo => /[-0-z\._]+/, :organization => /[-0-z\._]+/ }
end

app/models/github_connection.rb
class GithubConnection
  attr_reader :username, :token, :orgs, :repos, :issues
  
  def initialize(auth_data)
    @username = auth_data["username"]
    @token = auth_data["token"]
  end

  # GET request to get user's organizations; method called on instance in the organizations controller
  def get_organizations
    request = Typhoeus::Request.new(
      "https://api.github.com/user/orgs",
      headers: {Authorization: "token #{token}"}
    )
    response = request.run
    orgs = JSON.parse(response.body).map do |org| 
      org["login"]
    end
  end

  # GET request to get all of an organization's repos; method called on instance in the organizations controller
  def get_repos(organization)
    request = Typhoeus::Request.new(
      "https://api.github.com/orgs/#{organization}/repos",
      headers: {Authorization: "token #{token}"}
      )
    response = request.run
    repos = JSON.parse(response.body).map do |repo|
      repo["name"]
    end
  end

  # GET request to get all of a repos issues; method called on instance in the repos controller
  def get_issues(organization, repo)
    request = Typhoeus::Request.new(
      "https://api.github.com/repos/#{organization}/#{repo}/issues",
      headers: {Authorization: "token #{token}"}
      )
    response = request.run
    repos = JSON.parse(response.body).map do |issue|
      issue
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    # binding.pry
    self.create(
      :provider => auth["provider"],
      :uid => auth["uid"],
      :name => auth["info"]["name"],
      :username => auth["info"]["nickname"],
      :token => auth["credentials"]["token"]
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      nil
    end
  end

  helper_method :current_user

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :github_connection, only: [:index, :show]

  def index
    @username = current_user.username
    @organizations = @github.get_organizations
  end

  def show
    @repos = @github.get_repos(params[:organization])
  end

  private
  def github_connection
    @github = GithubConnection.new(current_user)
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_action :github_connection, only: [:show]

  def show
    @repo = params[:repo]
    @organization = params[:organization]
    @issues = @github.get_issues(@organization, @repo)
    respond_to do |format|
      format.html
    end
  end

  private
  def github_connection
    @github = GithubConnection.new(current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to organizations_path, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "Log Out", logout_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsRefactoring</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>

<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>

app/views/organizations/index.html.erb
<h1><%= @username %>'s Organizations</h1>

<% @organizations.each do |organization| %>
  <%= link_to organization, organization_path(:organization => organization) %><br>
<% end %>

app/views/organizations/show.html.erb
<h1> <%= @organization %> Repos </h1>

<% @repos.each do |repo| %>
  <%= link_to repo, repo_path(:repo => repo) %><br>
<% end %>

app/views/repos/show.html.erb
  <% if !@issues.empty? %>
    <% @issues.each do |issue|  %>
      <ul>
        <li><strong>Issue: <%= link_to issue["title"], issue["html_url"], :target => "_blank" %></strong></li>
        <li>Submitted by: <%= link_to issue["user"]["login"], issue["user"]["html_url"], :target => "_blank" %></li>
        <li>Date: <%= DateTime.parse(issue["created_at"]).to_formatted_s(:long) %></li>
        <li>Status: <%= issue["state"] %></li>
      <% if !issue["labels"].empty? %>
        <li>Labels: <%= issue["labels"][0]["name"] %></li>
      <% end %>
      </ul>
    <% end %>
  <% else %>
    <p><strong>There are no issues currently on this repo.</strong></p>
  <% end %>